services:
  mamexcalibur:
    build: .
    container_name: mamexcalibur
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file: .env
    environment:
      PORT: "3002"
    volumes:
      - ./konektor.db:/app/konektor.db
